name: UniversalBlocker
main: ru.Overwrite.noCmd.Main
author: Overwrite
version: 1.8
api-version: 1.13
commands:
  universalblocker:
    aliases: [ublocker, ub]   
permissions:
  ublocker.bypass.*:
    children:
      ublocker.bypass.commands: true
      ublocker.bypass.tabcomplete: true
      ublocker.bypass.numbers: true
      ublocker.bypass.symbols: true
      ublocker.bypass.chatsymbols: true